name: Deploy Next.js application

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
            uses: actions/checkout@v4
            - name: Create .env file